version: '3'
services:
  web:
    build: .
    ports:
      - "5000:8080"
    volumes:
      - db-data:/app
  db:
    image: postgres:14
    restart: always
    ports:
      - "7432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - db-data:/postgres

volumes:
  db-data: